/**
 * Reads graphql-ruby's class-based field DSL for the Ruby adapter. The
 * README covers discovery, `mutation:` and `resolver:` wiring, and how a
 * class name becomes a GraphQL type name.
 *
 * Every name graphql-ruby defines is set in this file, and the adapter
 * has none of them: the `field`, `type` and `argument` calls, the
 * `required:` and `camelize:` keywords with their defaults, and the
 * built-in scalars with their `GraphQL::Types::` spelling.
 */

import path from "node:path";

import { z } from "zod";

import { SCALAR_SHAPES } from "@suss/contract-graphql";

import type { GraphqlObjectFields, RubyPack } from "@suss/adapter-ruby";
import type { PackDeclaration } from "@suss/ir-core";

/**
 * The CLI checks a `-f graphql-ruby=config.json` file against this
 * schema. A config file may not set a key that only a dependency stub
 * fills.
 */
export const optionsSchema = z
  .object({
    /**
     * The directory the pack looks under for the class a `mutation:` or
     * `resolver:` field references, for example
     * `path.join(repoRoot, "app/graphql")`. A relative path resolves
     * against `configDirectory`, or the working directory when that is
     * unset.
     */
    root: z.string(),
    /**
     * The CLI fills this in with the config file's directory, or with the
     * directory the run reads when there is no file. A config file does
     * not set it.
     */
    configDirectory: z.string().optional(),
    /**
     * Base classes beyond the generated `Types::Base*` ones whose
     * subclasses declare GraphQL fields. A config file may not set this; a
     * dependency stub fills it.
     */
    baseClassNames: z.array(z.string()).optional(),
    /** The schema-wide camelCase default. A `field` or `argument` call's own `camelize:` keyword overrides it for that one name. */
    camelize: z.boolean().optional(),
  })
  .strict();

export type GraphqlRubyPackOptions = z.infer<typeof optionsSchema>;

/**
 * The library classes that graphql-ruby's generated base classes extend
 * or mix in. The ancestry walk stops at these, so a stub statement for
 * one adds nothing, and `suss infer stub` skips them.
 */
export const GRAPHQL_RUBY_ROOT_CLASS_NAMES: readonly string[] = [
  "GraphQL::Schema::Object",
  "GraphQL::Schema::Mutation",
  "GraphQL::Schema::Resolver",
  "GraphQL::Schema::Interface",
  "GraphQL::Schema::InputObject",
  "GraphQL::Schema::Enum",
  "GraphQL::Schema::Union",
  "GraphQL::Schema::Scalar",
];

/**
 * The type-level base classes `rails g graphql:install` generates. An
 * interface mixes its base in where other types extend theirs. The
 * generator also writes BaseArgument and BaseField, which back single
 * fields, so they are left out.
 */
const DEFAULT_BASE_CLASS_NAMES = [
  "Types::BaseObject",
  "Types::BaseInterface",
  "Types::BaseInputObject",
  "Types::BaseEnum",
  "Types::BaseUnion",
  "Types::BaseScalar",
];

/**
 * A `root` in a config file is relative to that file. Resolved against
 * the working directory, the same config would find nothing when run
 * from anywhere but the project root, and finding nothing looks the
 * same as a schema whose fields are all unwired.
 */
function rootDirectory(options: GraphqlRubyPackOptions): string {
  if (options.configDirectory === undefined || path.isAbsolute(options.root)) {
    return options.root;
  }
  return path.resolve(options.configDirectory, options.root);
}

export function graphqlRubyFramework(
  options: GraphqlRubyPackOptions,
): RubyPack {
  // The CLI passes on a pack config somebody wrote by hand, with no type
  // checking in front of it, so it can arrive here with nothing set.
  if (typeof options?.root !== "string" || options.root === "") {
    throw new Error(
      "it needs `root`, the directory a wired field's class is looked up under, and no default can be right: that is this project's own directory layout. A Rails app generated by the library keeps it at app/graphql.",
    );
  }

  const pattern: GraphqlObjectFields = {
    type: "graphqlObjectFields",
    baseClassNames: [
      ...DEFAULT_BASE_CLASS_NAMES,
      ...(options.baseClassNames ?? []),
    ],
    root: rootDirectory(options),
    pathConvention: "railsUnderscore",
    fieldCallName: "field",
    typeCallName: "type",
    argumentCallName: "argument",
    wiringKeywords: ["mutation", "resolver"],
    resolverMethodName: "resolve",
    ancestryRootClassNames: [...GRAPHQL_RUBY_ROOT_CLASS_NAMES],
    requiredKeyword: "required",
    // graphql-ruby registers an argument as required unless the call
    // opts out with `required: false`.
    requiredDefault: true,
    camelizeKeyword: "camelize",
    camelizeDefault: options.camelize ?? true,
    // The standard scalars come from the shared SDL table, so a contract
    // read from Ruby uses the same shapes as one read from SDL.
    // graphql-ruby also accepts Ruby's `Integer` class for `Int`.
    scalars: {
      ...SCALAR_SHAPES,
      Integer: { type: "number" },
    },
    scalarNamePrefixes: ["GraphQL::Types::"],
    typeNameConvention: "stripTypeSuffix",
    // RelayClassicMutation wraps every declared argument into one
    // `input` argument on the wire and adds clientMutationId to it.
    argumentWrapping: {
      ancestorClassName: "GraphQL::Schema::RelayClassicMutation",
      argumentName: "input",
      extraFields: {
        clientMutationId: { type: { type: "text" }, required: false },
      },
    },
  };
  return {
    name: "graphql-ruby",
    protocol: "http-graphql",
    discovery: [pattern],
    // A resolver that reads a model through the dataloader passes the model
    // as an argument, so the read is recorded against that model when a
    // storage pack in the same run recognizes it as one.
    loaders: [
      {
        loader: "dataloader",
        pick: "with",
        reads: ["load", "load_all", "request", "request_all"],
        shortcuts: [
          "dataload",
          "dataload_all",
          "dataload_record",
          "dataload_all_records",
        ],
        // The library runs `fetch` on the source class `with` was given,
        // so whatever that method reaches belongs to the field.
        source: { at: 0, method: "fetch" },
      },
    ],
  };
}

export const declares: PackDeclaration = {
  kind: "framework",
  package: "@suss/framework-graphql-ruby",
  dependencies: [{ ecosystem: "rubygems", name: "graphql" }],
  reads:
    "graphql-ruby class-based field DSL (Ruby). The pack follows \`mutation:\` and \`resolver:\` wiring one hop out to what the referenced class declares. It also records the model a resolver reads through \`dataloader\`, when a storage pack in the run recognizes that model.",
  configuration: {
    file: "suss.graphql-ruby.json",
    example: { root: "app/graphql" },
    required: true,
    why: "the directory a field's wired class is looked up under, read relative to this file. A Rails app generated by the library keeps its types and mutations under app/graphql.",
  },
};

export default graphqlRubyFramework;
