// @suss/framework-graphql-ruby: RubyPack for graphql-ruby's class-based
// field DSL.
//
// graphql-ruby declares a GraphQL type as a Ruby class extending a
// project's own base object class (generated by `rails g graphql:install`
// as `Types::BaseObject`, itself extending `GraphQL::Schema::Object`),
// with each field declared by a `field` call in the class body. The
// GraphQL type name comes from the class's own short name with a
// trailing `Type` stripped, the library's own `default_graphql_name`
// convention; there is nothing to configure for it. Root Query/Mutation
// fields wired through `mutation:` / `resolver:` read their declared
// shape from the referenced class's own file, located by Rails'
// constant-to-path convention under `root`.
//
// v0 scope: discovery and declared-shape reading only, per the
// language-adapters proposal's Ruby slice. `routes.rb` is a separate,
// much larger macro-expansion problem and is out of scope here.

import type { GraphqlObjectFields, RubyPack } from "@suss/adapter-ruby";

export interface GraphqlRubyPackOptions {
  /**
   * Directory the Rails constant-to-path convention resolves a
   * `mutation:` / `resolver:` field's referenced class against, e.g.
   * `path.join(repoRoot, "app/graphql")`. A project's own directory
   * layout, not something graphql-ruby names, so there is no default.
   */
  root: string;
  /**
   * Base class names beyond graphql-ruby's own generated
   * `Types::BaseObject` that also mark a class as declaring GraphQL
   * fields, e.g. a project's own intermediate base type. Named here the
   * way flask-restx's `wrapperModules` names a project's wrapper
   * alongside the library's own module.
   */
  baseClassNames?: string[];
  /**
   * graphql-ruby's own default for exposing a `field`/`argument`
   * symbol's snake_case name as camelCase on the schema. Defaults to
   * `true`, matching the library's own default; set to `false` when a
   * project's schema configures `camelize: false` schema-wide. A
   * `field` or `argument` call's own `camelize:` keyword always
   * overrides this for that one name, the same as it overrides
   * graphql-ruby's schema-wide setting at runtime.
   */
  camelize?: boolean;
}

/**
 * `Types::BaseObject` is graphql-ruby's own scaffolded convention: the
 * Rails generator that sets up a graphql-ruby project creates exactly
 * this class, extending `GraphQL::Schema::Object`, for every object
 * type in the schema to extend. It is the library's own naming, not a
 * particular project's choice, the same way flask-restx's `route` is
 * accepted as a default without a project naming it.
 */
const DEFAULT_BASE_CLASS_NAMES = ["Types::BaseObject"];

export function graphqlRubyFramework(
  options: GraphqlRubyPackOptions,
): RubyPack {
  const pattern: GraphqlObjectFields = {
    type: "graphqlObjectFields",
    baseClassNames: [
      ...DEFAULT_BASE_CLASS_NAMES,
      ...(options.baseClassNames ?? []),
    ],
    root: options.root,
    camelize: options.camelize ?? true,
  };
  return {
    name: "graphql-ruby",
    protocol: "http-graphql",
    discovery: [pattern],
  };
}

export default graphqlRubyFramework;
