// @suss/framework-graphql-ruby: RubyPack for graphql-ruby's class-based
// field DSL.
//
// graphql-ruby declares a GraphQL type as a Ruby class extending a
// project's own base object class, which `rails g graphql:install`
// generates as `Types::BaseObject` extending `GraphQL::Schema::Object`.
// Each field is declared by a `field` call in the class body.
//
// The GraphQL type name comes from the class's own short name with a
// trailing `Type` removed, which is the library's `default_graphql_name`
// convention, and the pack selects it as the adapter's
// `stripTypeSuffix` naming. Root Query and Mutation fields wired
// through `mutation:` or `resolver:` read their declared shape from the
// referenced class's own file, found by the Rails constant-to-path
// convention (the adapter's `railsUnderscore`) under `root`.
//
// Everything graphql-ruby defines is stated here rather than in the
// adapter: the `field`, `type` and `argument` calls, the `required:`
// and `camelize:` keywords and their defaults, and the built-in scalars
// with their `GraphQL::Types::` spelling. The adapter reads only these
// fields.
//
// This slice covers discovery and declared-shape reading. `routes.rb`
// is a separate and much larger macro-expansion problem, and it is out
// of scope here.

import path from "node:path";

import { SCALAR_SHAPES } from "@suss/contract-graphql";

import type { GraphqlObjectFields, RubyPack } from "@suss/adapter-ruby";

export interface GraphqlRubyPackOptions {
  /**
   * Directory a `mutation:` / `resolver:` field's referenced class is
   * looked up under, e.g. `path.join(repoRoot, "app/graphql")`.
   * Written relative, it is read relative to `configDirectory`, and
   * relative to the working directory when there is none.
   */
  root: string;
  /**
   * The directory of the config file these options came from. Whatever read
   * that file supplies this; it is not written in the file itself.
   */
  configDirectory?: string;
  /** Base classes beyond `Types::BaseObject` that also mark a class as declaring GraphQL fields. */
  baseClassNames?: string[];
  /** The schema-wide camelCase default. A `field` or `argument` call's own `camelize:` keyword overrides it for that one name. */
  camelize?: boolean;
}

/**
 * The type-level base classes `rails g graphql:install` scaffolds. A
 * type extends one of these, or mixes one in for an interface, so all
 * of them mark a definition as declaring GraphQL fields. The generator
 * also writes BaseArgument and BaseField, which back single fields
 * rather than types, so they are not in this list.
 */
const DEFAULT_BASE_CLASS_NAMES = [
  "Types::BaseObject",
  "Types::BaseInterface",
  "Types::BaseInputObject",
  "Types::BaseEnum",
  "Types::BaseUnion",
  "Types::BaseScalar",
];

/**
 * A `root` written in a config file is written relative to that file.
 * Resolving it against the working directory instead makes the same
 * config find nothing from anywhere but the project root, and finding
 * nothing looks exactly like a schema whose fields are all unwired.
 */
function rootDirectory(options: GraphqlRubyPackOptions): string {
  if (options.configDirectory === undefined || path.isAbsolute(options.root)) {
    return options.root;
  }
  return path.resolve(options.configDirectory, options.root);
}

export function graphqlRubyFramework(
  options: GraphqlRubyPackOptions,
): RubyPack {
  // The CLI passes on a pack config somebody wrote by hand, with no type
  // checking in front of it, so it can arrive here with nothing set.
  if (typeof options?.root !== "string" || options.root === "") {
    throw new Error(
      "it needs `root`, the directory a wired field's class is looked up under, and no default can be right: that is this project's own directory layout. A Rails app generated by the library keeps it at app/graphql.",
    );
  }

  const pattern: GraphqlObjectFields = {
    type: "graphqlObjectFields",
    baseClassNames: [
      ...DEFAULT_BASE_CLASS_NAMES,
      ...(options.baseClassNames ?? []),
    ],
    root: rootDirectory(options),
    pathConvention: "railsUnderscore",
    fieldCallName: "field",
    typeCallName: "type",
    argumentCallName: "argument",
    wiringKeywords: ["mutation", "resolver"],
    resolverMethodName: "resolve",
    // The classes graphql-ruby's own generated base classes extend or
    // mix in. A project's chain ends at one of them.
    ancestryRootClassNames: [
      "GraphQL::Schema::Object",
      "GraphQL::Schema::Mutation",
      "GraphQL::Schema::Resolver",
      "GraphQL::Schema::Interface",
      "GraphQL::Schema::InputObject",
      "GraphQL::Schema::Enum",
      "GraphQL::Schema::Union",
      "GraphQL::Schema::Scalar",
    ],
    requiredKeyword: "required",
    // graphql-ruby registers an argument as required unless the call
    // opts out with `required: false`.
    requiredDefault: true,
    camelizeKeyword: "camelize",
    camelizeDefault: options.camelize ?? true,
    // The standard scalars come from the shared SDL table, so a
    // contract read from Ruby compares against one read from SDL
    // without a vocabulary mismatch. graphql-ruby accepts Ruby's own
    // `Integer` class as a synonym for its `Int` scalar.
    scalars: {
      ...SCALAR_SHAPES,
      Integer: { type: "number" },
    },
    scalarNamePrefixes: ["GraphQL::Types::"],
    typeNameConvention: "stripTypeSuffix",
  };
  return {
    name: "graphql-ruby",
    protocol: "http-graphql",
    discovery: [pattern],
  };
}

export default graphqlRubyFramework;
